"""One storage seam: SQLite on a laptop, Postgres on a dyno.

Heroku's filesystem is ephemeral. It is wiped on every restart — at least
daily, plus on each deploy and each config change — so a SQLite file there
means every user, session, FPL link, vaulted cookie and saved squad is
destroyed several times a day. That is the whole reason this module exists.

The design goal is that `accounts.py` should not care. Its thirty-nine queries
are already standard SQL (the upserts use `ON CONFLICT ... DO UPDATE`, which
Postgres and SQLite both speak), so rather than fork the module this wraps the
connection and translates the handful of things that genuinely differ:

- **Placeholders.** SQLite wants `?`, psycopg wants `%s`.
- **Generated ids.** `cursor.lastrowid` does not exist on Postgres; an
  `INSERT` that needs its new id gets `RETURNING id` appended.
- **Types.** Declared in `SCHEMA` in SQLite's spelling and rewritten for
  Postgres — see `_PG_TYPES` for why `REAL` is the dangerous one.
- **Row access.** Both yield mappings keyed by column name.

Provider-agnostic on purpose: it speaks to anything with a `DATABASE_URL`, so
the choice of host is a config value rather than a decision baked into code.
"""

from __future__ import annotations

import os
import re
import sqlite3
import threading
from pathlib import Path
from typing import Any, Iterable, Sequence

DEFAULT_SQLITE_PATH = Path.home() / ".local" / "share" / "fpl" / "app.db"


def database_url() -> str:
    return os.getenv("DATABASE_URL", "").strip()


def is_postgres() -> bool:
    return database_url().startswith(("postgres://", "postgresql://"))


def _normalised_url() -> str:
    """psycopg rejects the `postgres://` scheme some providers still hand out."""
    url = database_url()
    if url.startswith("postgres://"):
        url = "postgresql://" + url[len("postgres://") :]
    # Managed Postgres is TLS-only in practice, and psycopg will happily
    # connect in the clear if the server allows it. Ask for TLS unless the URL
    # already says otherwise.
    if "sslmode=" not in url:
        url += ("&" if "?" in url else "?") + "sslmode=require"
    return url


# ---------------------------------------------------------------- schema

# Written in SQLite's spelling; `_for_postgres` rewrites it. Kept as one list
# of statements rather than a script because psycopg executes one at a time.
SCHEMA: tuple[str, ...] = (
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY,
        email TEXT NOT NULL UNIQUE,
        -- Empty string means "no password set" (a Google-only account).
        password_hash TEXT NOT NULL,
        google_sub TEXT,
        created_at REAL NOT NULL,
        deadline_email INTEGER NOT NULL DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS sessions (
        token TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        created_at REAL NOT NULL,
        expires_at REAL NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS fpl_links (
        user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        entry_id INTEGER NOT NULL,
        team_name TEXT,
        manager_name TEXT,
        linked_at REAL NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS password_resets (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        created_at REAL NOT NULL,
        expires_at REAL NOT NULL,
        used_at REAL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS fpl_cookies (
        user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        ciphertext BLOB NOT NULL,
        updated_at REAL NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS saved_squads (
        user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        element_ids TEXT NOT NULL,
        bench_ids TEXT NOT NULL,
        source TEXT NOT NULL,
        updated_at REAL NOT NULL
    )
    """,
)

# Applied *after* the column migrations in `accounts.init_db`, not with the
# tables. An index names a column, and on a database that predates that column
# creating it first fails — which is exactly the upgrade path this has to
# survive.
INDEXES: tuple[str, ...] = (
    # Both backends permit many NULLs in a unique index, so password-only
    # accounts coexist fine.
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_users_google_sub ON users (google_sub)",
    # Sessions and reset tokens are looked up by user when revoking every
    # session after a password reset.
    "CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions (user_id)",
)

_PG_TYPES: tuple[tuple[str, str], ...] = (
    # SQLite's rowid alias becomes a real identity column.
    (r"\bid INTEGER PRIMARY KEY\b", "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
    (r"\bBLOB\b", "BYTEA"),
    # The one that would corrupt data silently: Postgres REAL is float4, about
    # seven significant digits. An epoch timestamp needs ten, so every
    # created_at and expires_at would be rounded to the nearest few minutes —
    # enough to expire a fresh session or resurrect a used reset token.
    (r"\bREAL\b", "DOUBLE PRECISION"),
    (r"\bINTEGER\b", "BIGINT"),
)


def _for_postgres(statement: str) -> str:
    for pattern, replacement in _PG_TYPES:
        statement = re.sub(pattern, replacement, statement)
    return statement


# ---------------------------------------------------------------- connection

_sqlite_lock = threading.Lock()


class Cursor:
    """Uniform cursor. `lastrowid` works on both backends.

    Anything not named here is forwarded to the underlying driver cursor, so a
    caller reaching for a DB-API attribute this wrapper hasn't thought of gets
    the real thing rather than an AttributeError. Wrapping a driver means
    re-exporting its interface, and enumerating that by hand is a list you
    discover you got wrong at runtime.
    """

    def __init__(self, raw, lastrowid: int | None):
        self._raw = raw
        self.lastrowid = lastrowid

    def fetchone(self):
        return self._raw.fetchone()

    def fetchall(self):
        return self._raw.fetchall()

    def __iter__(self):
        return iter(self._raw)

    def __getattr__(self, name):
        return getattr(self._raw, name)


class Connection:
    """A connection that speaks the same SQL to either backend."""

    def __init__(self, raw, postgres: bool):
        self._raw = raw
        self.postgres = postgres

    def execute(self, sql: str, params: Sequence[Any] = ()) -> Cursor:
        if not self.postgres:
            raw = self._raw.execute(sql, params)
            # Taken from the driver, not defaulted: an id of None here would
            # silently insert a NULL user_id into every dependent row.
            return Cursor(raw, raw.lastrowid)

        translated = _to_pg_placeholders(sql)
        wants_id = _is_insert_needing_id(translated)
        if wants_id:
            translated = translated.rstrip().rstrip(";") + " RETURNING id"
        cursor = self._raw.cursor()
        cursor.execute(translated, tuple(params))

        lastrowid = None
        if wants_id:
            row = cursor.fetchone()
            # A DO NOTHING conflict returns no row; the caller sees None rather
            # than an id belonging to somebody else.
            lastrowid = row["id"] if row else None
        return Cursor(cursor, lastrowid)

    def executemany(self, sql: str, seq: Iterable[Sequence[Any]]) -> None:
        if not self.postgres:
            self._raw.executemany(sql, seq)
            return
        cursor = self._raw.cursor()
        cursor.executemany(_to_pg_placeholders(sql), [tuple(p) for p in seq])

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def close(self) -> None:
        self._raw.close()

    def __enter__(self) -> "Connection":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        # Mirrors sqlite3's context manager: commit on success, roll back on
        # error. The connection is closed either way, because on Postgres a
        # leaked connection is a leaked server-side session and, on a provider
        # that sleeps when idle, one that never lets it sleep.
        try:
            if exc_type is None:
                self._raw.commit()
            else:
                self._raw.rollback()
        finally:
            self._raw.close()


_PLACEHOLDER_RE = re.compile(
    r"""
    '(?:[^']|'')*'      # single-quoted literal, '' escape included
    | "(?:[^"]|"")*"    # quoted identifier
    | --[^\n]*          # line comment
    | (\?)              # ... and finally, a real placeholder
    """,
    re.VERBOSE,
)


def _to_pg_placeholders(sql: str) -> str:
    """`?` → `%s`, without touching question marks inside strings or comments.

    A blunt `sql.replace("?", "%s")` corrupts any literal containing one, and
    `%` in a literal would then be read by psycopg as a format specifier.
    """
    def swap(match: re.Match) -> str:
        if match.group(1) is None:
            return match.group(0)
        return "%s"

    return _PLACEHOLDER_RE.sub(swap, sql)


def _is_insert_needing_id(sql: str) -> bool:
    """Only plain inserts into `users`, the one table with a generated id.

    Narrow on purpose: appending RETURNING to an insert whose table has no `id`
    column is an error, and every other table here uses a natural key.
    """
    stripped = sql.strip().lstrip("(").lstrip()
    if not stripped[:6].upper().startswith("INSERT"):
        return False
    if "RETURNING" in stripped.upper():
        return False
    return re.search(r"INSERT\s+INTO\s+users\b", stripped, re.IGNORECASE) is not None


def connect(sqlite_path: Path | None = None) -> Connection:
    if is_postgres():
        import psycopg
        from psycopg.rows import dict_row

        def rows(cursor):
            """dict rows, with BYTEA handed back as `bytes`.

            psycopg yields `memoryview` for binary columns. sqlite3 yields
            `bytes`, and Fernet only accepts `bytes` — so without this the
            cookie vault would raise on Postgres and nowhere else, which is
            exactly the class of bug a second backend introduces quietly.
            """
            base = dict_row(cursor)

            def make(values):
                row = base(values)
                return {
                    key: bytes(value) if isinstance(value, memoryview) else value
                    for key, value in row.items()
                }

            return make

        raw = psycopg.connect(_normalised_url(), row_factory=rows)
        return Connection(raw, postgres=True)

    path = Path(sqlite_path or os.getenv("FPL_APP_DB") or DEFAULT_SQLITE_PATH)
    path.parent.mkdir(parents=True, exist_ok=True)
    raw = sqlite3.connect(path)
    raw.row_factory = sqlite3.Row
    raw.execute("PRAGMA foreign_keys = ON")
    return Connection(raw, postgres=False)


def init_schema(conn: Connection) -> None:
    for statement in SCHEMA:
        conn.execute(_for_postgres(statement) if conn.postgres else statement)


def init_indexes(conn: Connection) -> None:
    for statement in INDEXES:
        conn.execute(statement)


def lock():
    """Serialise writers on SQLite only.

    SQLite is one file and one writer; Postgres does its own locking, and
    holding a process-wide mutex there would serialise a database built to
    handle concurrency.
    """
    return _sqlite_lock if not is_postgres() else _NullLock()


class _NullLock:
    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False
