"""The storage seam: same SQL, two backends.

Heroku's filesystem is ephemeral, so a SQLite file in production is destroyed
several times a day and takes every account with it. This module is what lets
`accounts.py` keep its thirty-nine queries unchanged while running on Postgres.

The translation tests below need no database and are where the silent-corruption
bugs live. The integration tests need a real Postgres and skip without one:

    TEST_DATABASE_URL='postgresql://.../fpl_test' pytest tests/test_db.py

Deliberately *not* `DATABASE_URL`. These tests drop every table on teardown, so
pointing them at the variable production also reads would destroy the live
database — which is exactly what happened once, and why the fixture below now
refuses to run against it.
"""

import os
import re
import time

import pytest

from engine import accounts, db


# ------------------------------------------------------------ translation


class TestPlaceholders:
    def test_question_marks_become_percent_s(self):
        assert (
            db._to_pg_placeholders("SELECT * FROM users WHERE id = ? AND email = ?")
            == "SELECT * FROM users WHERE id = %s AND email = %s"
        )

    def test_a_question_mark_inside_a_literal_is_left_alone(self):
        """A blunt str.replace corrupts any literal containing one — and the
        stray %s it leaves behind is then read by psycopg as a placeholder,
        so the query fails with a confusing arity error rather than obviously."""
        sql = "SELECT ? WHERE note = 'really?'"

        assert db._to_pg_placeholders(sql) == "SELECT %s WHERE note = 'really?'"

    def test_a_question_mark_in_a_comment_is_left_alone(self):
        sql = "SELECT ?\n-- is this right?\nFROM users"

        assert db._to_pg_placeholders(sql).count("%s") == 1

    def test_an_escaped_quote_does_not_end_the_literal_early(self):
        sql = "SELECT ? WHERE name = 'O''Brien?'"

        assert db._to_pg_placeholders(sql) == "SELECT %s WHERE name = 'O''Brien?'"


class TestTypeMapping:
    def test_real_becomes_double_precision(self):
        """The one that would corrupt data silently.

        Postgres REAL is float4 — about seven significant digits. An epoch
        timestamp needs ten, so every created_at and expires_at would be
        rounded to the nearest few minutes: enough to expire a fresh session,
        or to un-expire a used password-reset token.
        """
        assert "DOUBLE PRECISION" in db._for_postgres("created_at REAL NOT NULL")
        assert "REAL" not in db._for_postgres("created_at REAL NOT NULL")

    def test_float4_really_would_lose_the_precision_this_guards(self):
        """Not an assumption about Postgres — arithmetic anyone can check."""
        import struct

        now = time.time()
        as_float4 = struct.unpack("f", struct.pack("f", now))[0]

        assert abs(as_float4 - now) > 1.0, "float4 cannot hold an epoch second"

    def test_the_rowid_alias_becomes_a_real_identity_column(self):
        result = db._for_postgres("id INTEGER PRIMARY KEY")

        assert "GENERATED BY DEFAULT AS IDENTITY" in result

    def test_blobs_become_bytea(self):
        assert "BYTEA" in db._for_postgres("ciphertext BLOB NOT NULL")

    def test_every_schema_statement_survives_translation(self):
        for statement in db.SCHEMA:
            translated = db._for_postgres(statement)
            assert "BLOB" not in translated
            # 'REAL' must not survive as a standalone type name.
            assert " REAL " not in translated


class TestReturningId:
    def test_only_the_table_with_a_generated_id_gets_returning(self):
        assert db._is_insert_needing_id("INSERT INTO users (email) VALUES (?)")
        # Every other table uses a natural key and has no `id` column at all,
        # so appending RETURNING id would be an error rather than a nicety.
        assert not db._is_insert_needing_id(
            "INSERT INTO sessions (token, user_id) VALUES (?, ?)"
        )
        assert not db._is_insert_needing_id("SELECT id FROM users")

    def test_an_existing_returning_clause_is_not_doubled(self):
        assert not db._is_insert_needing_id(
            "INSERT INTO users (email) VALUES (?) RETURNING id"
        )


# ------------------------------------------------------------- integration

TEST_DATABASE_URL = os.getenv("TEST_DATABASE_URL", "").strip()

# Captured at import, which is the only moment it is still visible: the autouse
# fixture in conftest deletes DATABASE_URL from the environment before any test
# runs. Reading it inside the fixture therefore always saw an empty string, and
# the safety check below silently passed — which is how these tests dropped the
# production tables a second time after the guard was added.
LIVE_DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
postgres_only = pytest.mark.skipif(
    not TEST_DATABASE_URL.startswith(("postgres://", "postgresql://")),
    reason="set TEST_DATABASE_URL to a throwaway Postgres database to run these",
)


@pytest.fixture
def pg(monkeypatch):
    """A clean schema on a throwaway database, dropped again afterwards.

    The guard is not paranoia. These tests DROP TABLE on teardown, and pointed
    at production they delete every account — silently, in a green test run.
    """
    if LIVE_DATABASE_URL and LIVE_DATABASE_URL == TEST_DATABASE_URL:
        pytest.fail(
            "TEST_DATABASE_URL is the same database as DATABASE_URL. These "
            "tests drop every table; point them at a throwaway database."
        )
    monkeypatch.setenv("DATABASE_URL", TEST_DATABASE_URL)
    _drop_everything()
    accounts.init_db()
    yield
    _drop_everything()


def _schema_tables() -> list[str]:
    """Every table the app creates, read off the schema itself.

    Hardcoding the list meant it went stale the moment a table was added: the
    LLM budget tables were not dropped between tests, so counts leaked from one
    test into the next and the failures pointed at the wrong code.
    """
    names = []
    for statement in db.SCHEMA:
        match = re.search(r"CREATE TABLE IF NOT EXISTS (\w+)", statement)
        if match:
            names.append(match.group(1))
    return names


def _drop_everything() -> None:
    with db.connect() as conn:
        for table in _schema_tables():
            conn.execute(f"DROP TABLE IF EXISTS {table} CASCADE")


@postgres_only
def test_the_whole_account_lifecycle_works_on_postgres(pg):
    user = accounts.register("nish@example.com", "a-decent-password")
    assert user["id"] is not None, "a NULL id would orphan every dependent row"

    token = accounts.authenticate("nish@example.com", "a-decent-password")
    assert accounts.user_for_token(token)["email"] == "nish@example.com"

    accounts.link_fpl(user["id"], 2670555, "__here_to_win__", "Nishant Gerald")
    assert accounts.fpl_link(user["id"])["entry_id"] == 2670555


@postgres_only
def test_a_second_link_updates_rather_than_duplicates(pg):
    """ON CONFLICT DO UPDATE is the one piece of SQL that differs most between
    engines; this proves the shared spelling works on Postgres too."""
    user = accounts.register("nish@example.com", "a-decent-password")

    accounts.link_fpl(user["id"], 111, "First", "Nishant")
    accounts.link_fpl(user["id"], 222, "Second", "Nishant")

    assert accounts.fpl_link(user["id"])["entry_id"] == 222


@postgres_only
def test_deleting_a_user_takes_their_sessions_with_them(pg):
    """The property that decided Postgres over Aurora DSQL.

    DSQL has no foreign keys, so this cascade would have to be re-implemented
    in application code — and a missed path leaves a revoked user's session
    tokens working, which is a security bug rather than untidiness.
    """
    user = accounts.register("nish@example.com", "a-decent-password")
    token = accounts.authenticate("nish@example.com", "a-decent-password")
    accounts.link_fpl(user["id"], 2670555, "Team", "Nishant")

    with db.connect() as conn:
        conn.execute("DELETE FROM users WHERE id = ?", (user["id"],))

    assert accounts.user_for_token(token) is None
    with db.connect() as conn:
        leftovers = conn.execute(
            "SELECT COUNT(*) AS n FROM sessions WHERE user_id = ?", (user["id"],)
        ).fetchone()
    assert leftovers["n"] == 0


@postgres_only
def test_timestamps_survive_the_round_trip_to_the_second(pg):
    """Guards the float4 trap from the other side: a stored expiry that drifts
    by minutes silently expires live sessions."""
    user = accounts.register("nish@example.com", "a-decent-password")
    accounts.authenticate("nish@example.com", "a-decent-password")

    with db.connect() as conn:
        row = conn.execute(
            "SELECT created_at, expires_at FROM sessions WHERE user_id = ?",
            (user["id"],),
        ).fetchone()

    assert abs(row["created_at"] - time.time()) < 60
    span = row["expires_at"] - row["created_at"]
    assert abs(span - accounts.SESSION_TTL_SECONDS) < 1


@postgres_only
def test_the_cookie_vault_round_trips_binary_through_bytea(pg):
    """SQLite BLOB becomes BYTEA; psycopg hands back `memoryview`, which is not
    `bytes` and would break Fernet if it reached it unconverted."""
    user = accounts.register("nish@example.com", "a-decent-password")

    accounts.store_cookie(user["id"], "pl_profile=abc123")

    assert accounts.cookie_for(user["id"]) == "pl_profile=abc123"


@postgres_only
def test_init_db_is_safe_to_run_twice(pg):
    """It runs on every boot, and a dyno boots constantly."""
    accounts.init_db()
    accounts.init_db()

    user = accounts.register("nish@example.com", "a-decent-password")
    assert user["id"] is not None


class TestPercentEscaping:
    """psycopg reads a bare `%` as a format specifier and refuses the query.

    Not currently hit — no query in accounts.py contains one — but the first
    `LIKE 'prefix-%'` anyone writes would fail only on Postgres, and only in
    production.
    """

    def test_a_literal_percent_is_doubled_when_parameters_are_passed(self):
        sql = "DELETE FROM users WHERE email LIKE 'check-%' AND id = ?"

        assert (
            db._to_pg_placeholders(sql, has_params=True)
            == "DELETE FROM users WHERE email LIKE 'check-%%' AND id = %s"
        )

    def test_a_literal_percent_is_left_alone_without_parameters(self):
        """psycopg skips placeholder parsing for an argument-less query, so
        escaping there would leave a literal %% in the data."""
        sql = "DELETE FROM users WHERE email LIKE 'check-%'"

        assert db._to_pg_placeholders(sql, has_params=False) == sql


@postgres_only
def test_a_like_pattern_works_against_the_real_server(pg):
    accounts.register("keep-me@example.com", "a-decent-password")
    accounts.register("drop-me@example.com", "a-decent-password")

    with db.connect() as conn:
        conn.execute(
            "DELETE FROM users WHERE email LIKE 'drop-%' AND id > ?", (0,)
        )
        remaining = conn.execute("SELECT email FROM users").fetchall()

    assert [row["email"] for row in remaining] == ["keep-me@example.com"]


# ------------------------------------------------- the LLM budget, shared


@postgres_only
def test_the_daily_ceiling_is_shared_not_per_worker(pg, monkeypatch):
    """On a dyno the file version counted nothing.

    The filesystem is wiped on every restart, so a 250-a-day ceiling reset
    several times a day — and each of the three gunicorn workers kept its own
    idea of the total besides, multiplying the limit by the worker count.
    """
    from engine import llm_budget

    monkeypatch.setattr(llm_budget, "DAILY_CALL_CEILING", 3)

    for _ in range(3):
        llm_budget._spend_one("vision")

    with pytest.raises(llm_budget.BudgetExhausted):
        llm_budget._spend_one("vision")

    assert llm_budget.spent_today()["total"] == 3
    assert llm_budget.remaining_today() == 0


@postgres_only
def test_concurrent_spends_cannot_overshoot_the_ceiling(pg, monkeypatch):
    """The property that makes this worth doing at all.

    Read-then-write lets two workers both see 249 and both spend. The check and
    the increment are one statement precisely so the refusal is atomic — a
    failure loop is the shape of traffic a ceiling exists to stop.
    """
    import concurrent.futures as futures

    from engine import llm_budget

    monkeypatch.setattr(llm_budget, "DAILY_CALL_CEILING", 10)

    def spend():
        try:
            llm_budget._spend_one("vision")
            return True
        except llm_budget.BudgetExhausted:
            return False

    with futures.ThreadPoolExecutor(max_workers=12) as pool:
        granted = sum(pool.map(lambda _: spend(), range(40)))

    assert granted == 10, f"{granted} calls allowed against a ceiling of 10"
    assert llm_budget.spent_today()["total"] == 10


@postgres_only
def test_the_breakdown_by_kind_is_kept(pg, monkeypatch):
    from engine import llm_budget

    monkeypatch.setattr(llm_budget, "DAILY_CALL_CEILING", 50)

    llm_budget._spend_one("vision")
    llm_budget._spend_one("vision")
    llm_budget._spend_one("fcps")

    assert llm_budget.spent_today()["by_kind"] == {"vision": 2, "fcps": 1}


@postgres_only
def test_the_hourly_client_throttle_is_shared(pg, monkeypatch):
    from engine import llm_budget

    monkeypatch.setattr(llm_budget, "CLIENT_CALLS_PER_HOUR", 3)

    for _ in range(3):
        llm_budget.check_client("198.51.100.7")

    with pytest.raises(llm_budget.ClientThrottled):
        llm_budget.check_client("198.51.100.7")

    # Another caller is unaffected — it is a per-client share, not a global one.
    llm_budget.check_client("198.51.100.8")


@postgres_only
def test_calls_outside_the_window_stop_counting(pg, monkeypatch):
    """Otherwise the throttle is a lifetime ban rather than an hourly one."""
    from engine import llm_budget

    monkeypatch.setattr(llm_budget, "CLIENT_CALLS_PER_HOUR", 2)
    llm_budget.check_client("198.51.100.9")
    llm_budget.check_client("198.51.100.9")

    with db.connect() as conn:
        conn.execute(
            "UPDATE llm_client_calls SET called_at = called_at - ?",
            (llm_budget._CLIENT_WINDOW_SECONDS + 60,),
        )

    llm_budget.check_client("198.51.100.9")


@postgres_only
def test_a_status_read_never_raises_even_with_no_rows(pg):
    from engine import llm_budget

    assert llm_budget.spent_today() == {
        "date": llm_budget._today(),
        "total": 0,
        "by_kind": {},
    }
